#"name of exercise","target area","difficulty(int)","category"(weightlifting,aerobic,bodybuilding)
"Chest Bench Press","Chest",2,"weightlifting"
"Chest Fly","Chest",3,"aerobic"
"Decline Chest Press","Chest",2,"bodybuilding"
"Iso lateral Chest","Chest",1,"bodybuilding"
"Triceps Press","Triceps".1,"bodybuilding"
"EZ Bar Skullcrushers","Triceps",2,"weightlifting"
"Over - Head Triceps","Triceps",1,"bodybuilding"
"Pull Ups","Back",3,"bodybuilding"
"Wide Push Ups","Chest",0,"aerobic"
"Pike Push Ups","Shoulders",0,"aerobic"
"Knee to Elbow Push","abs",0,"aerobic"
"Diamond Push Ups","Triceps",0,"aerobic"
"Biceps Curls with Machine","Biceps",2,"bodybuilding"
"Bicep Curls","Biceps",3,"weightlifting"
"Seated Back Rows","Back",3,"bodybuilding"
"Lat Pull Down (Mini Grip)","Back",1,"bodybuilding"
"Lat Pull Down (Wide Grip)","Back",2,"weightlifting"
"Back Extension","Back",3,"weightlifting"
"Back Power Lift","Back",3,"weightlifting"
"Bicep Side Curl","Biceps",2,"bodybuilding"
"21s Arm Destruction","Biceps",2,"bodybuilding"
"Hammer Curls","Biceps",1,"bodybuilding"
"Shoulder Press", "Shoulders",2,"weightlifting"
"Vertical Shoulder Press","Shoulders",2,"weightlifting"
"Horizontal Shoulder Press","Shoulders",2,"weightlifting"
"Vertical-Shoulder Press","Shoulders",3,"bodybuilding"
"Horizontal-Shoulder Press","Shoulders",3,"bodybuilding"
"Shoulder Shrugs","Shoulders",0,"bodybuilding"
"Cycling","Legs",1,"aerobics"
"Cycling-Beginners","Legs",0,"aerobics"
"Jogging-Beginners","Legs",0,"aerobics"
"Jogging","Legs,"1,"aerobics"
"Swimming","Legs",2,"aerobics"
"Front Squat with Barbell","Legs",3,"weightlifting"
"Front Squat","Legs",2,"bodybuilding"
"Bulgarian Split Squat","Legs",3,"weightlifting"
"Romanian Deadlift","Legs",3,"weightlifting"
"Bulgarian-Split-Squat"."Legs",3,"bodybuilding"
"Romanian-Deadlift,","Legs"3,"bodybuilding"
"Swiss Ball Leg Curl",2,"bodybuilding"
"Russian ab Twists","Abs",1,"bodybuilding"
"Single Leg Romanian-Deadlift","Legs",2,"bodybuilding"
"Bodyweight Calf Raise","Legs",1,"aerobics"
"Bodybuilding Calf Raise","Legs",2,"bodybuilding"
"Walking Lunge","Legs",3,"bodybuilding"
"In Place Lunges","Legs",0,"bodybuilding"
"Pause Squat","Legs",2,"weightlifting"
"Reverse Lunge","Legs",1,"aerobics"
"Dumbbell Squat","Legs",1,"bodybuilding"
"High Knees","Legs",0,"aerobics"
"High Knee kicks","Legs",1,"aerobics"
"Kettlebell Swing","Legs",2,"weightlifting"
"Goblet Squats","Legs",3,"weightlifting"
"Jump Squat","Legs",2,"aerobics"
"Single Leg Glute Bridge","Legs",1,"aerobics"
"Sit Ups","Abs",0,"aerobics"
"Crunches","Abs",1,"aerobics"
"Reverse Crunches","Abs",2,"aerobics"
"High Crunches","Abs",3,"aerobics"
"Knee to Elbow Crunches","Abs",0,"bodybuilding"
"Elbow Plank","Abs",2,"bodybuilding"
"Side Elbow Plank","Abs",1,"bodybuilding"











